### ISSUE TITLE
只能提取3倍的图片

### ISSUE THREAD

**Issue by zhoujie903** [crespoxiao/iOSImagesExtractor#1]
用截止提交为7e9b950的版本编译出来的iOS Images Extractor.app只能提取3倍的图片

**Comment by zhoujie903** [comment]
补充下：是对Xcode编译来的xxx.app里的Assets.car，只能提取3倍的图片。我的Xcode是Version 8.3.2 (8E2002)，macOS Version10.12.4 (16E195). 从app store上下载的ipa是能正确提取2倍和3倍图片的

**Comment by crespoxiao** [comment]
@zhoujie903    只能提取 2x 图片吧，是 3x 图片拿不到。 我暂时也没办法呢，找遍了GitHub都没有找到好的办法 。 先找个低版本的 Xcode。

**Comment by crespoxiao** [comment]
@zhoujie903    可以试试我的这个脚本：https://gist.github.com/crespoxiao/82c2fcc0fd08132e8b49e5116b282ab8

**Comment by zhoujie903** [comment]
@crespoxiao  我对你的脚本有疑问
`# 使用示例 ./pdf2png.sh xx.xcassets`
疑问：xcassets本来就是没编译过的，现在的问题是iOS Images Extractor.app只能提取Xcode编译来的xxx.app里的Assets.car里的3倍图片。你的脚本用意是什么？是转从xcassets提取图片文件?

**Comment by crespoxiao** [comment]
@zhoujie903  只针对自己的工程，处理掉历史遗留的矢量图，对于提取别人的应用里的@3x图片暂时无能为力。
